#!/bin/bash
set -e

echo "🔧 Automating remaining feasible tasks (excluding currency, module split, cloud, expert mode)"

# ----------------------------------------------------------------------
# 1. Translate Urdu and Malay JSON files using a local Python script
#    (uses googletrans if installed, otherwise prints manual instructions)
# ----------------------------------------------------------------------
echo "1. Translating ur.json and ms.json ..."

cat > /tmp/translate_json.py << 'PY_EOF'
import json
import sys
import os

try:
    from googletrans import Translator
    translator = Translator()
    use_api = True
except ImportError:
    use_api = False

def translate_file(src_file, dest_file, target_lang):
    with open(src_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    new_data = {}
    for key, value in data.items():
        if use_api and value:
            try:
                translated = translator.translate(value, dest=target_lang).text
                new_data[key] = translated
            except:
                new_data[key] = value + " (need translation)"
        else:
            new_data[key] = value + " (auto-translate not available – please translate manually)"
    with open(dest_file, 'w', encoding='utf-8') as f:
        json.dump(new_data, f, ensure_ascii=False, indent=2)
    print(f"Updated {dest_file}")

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python translate_json.py <src> <dest> <lang>")
        sys.exit(1)
    translate_file(sys.argv[1], sys.argv[2], sys.argv[3])
PY_EOF

# Try to install googletrans if not present
python3 -m pip install googletrans==4.0.0-rc1 --quiet 2>/dev/null || echo "⚠️ Could not install googletrans; using manual placeholders."

# Translate Urdu (ur)
python3 /tmp/translate_json.py lib/i18n/locales/en.json lib/i18n/locales/ur.json ur
# Translate Malay (ms)
python3 /tmp/translate_json.py lib/i18n/locales/en.json lib/i18n/locales/ms.json ms

# ----------------------------------------------------------------------
# 2. Improve legal report (PDF) generation
# ----------------------------------------------------------------------
echo "2. Improving legal report PDF formatting..."

cat > components/LegalReportGenerator.tsx << 'REPORT_EOF'
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform, Alert } from 'react-native';
import { formatCurrency } from '../lib/utils/currency';

export async function generateLegalReport(result: any, madhab: string) {
  const today = new Date().toLocaleDateString('ar-EG', { year: 'numeric', month: 'long', day: 'numeric' });
  const caseNumber = `MER-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
  const disclaimer = `هذا التقرير تم إنشاؤه بواسطة تطبيق "ميراث" (Merath). 
  يرجى مراجعة عالم شرعي موثوق لتأكيد صحة التوزيع. 
  This report is generated by Merath App. Please consult a qualified scholar for legal validation.`;

  const html = `
  <html>
  <head>
    <meta charset="UTF-8">
    <style>
      body { font-family: 'Arial', 'Tahoma', sans-serif; padding: 30px; direction: rtl; }
      .header { text-align: center; border-bottom: 2px solid #0D7C66; padding-bottom: 10px; margin-bottom: 20px; }
      .title { font-size: 24px; font-weight: bold; color: #0D7C66; }
      .subtitle { font-size: 14px; color: #666; }
      .case-number { font-size: 12px; color: #999; text-align: left; direction: ltr; margin-top: 5px; }
      .section { margin-bottom: 20px; }
      .table { width: 100%; border-collapse: collapse; }
      .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: right; }
      .table th { background-color: #0D7C66; color: white; }
      .signature { margin-top: 40px; border-top: 1px solid #000; padding-top: 10px; font-size: 12px; text-align: center; }
      .disclaimer { margin-top: 20px; font-size: 10px; color: #777; text-align: center; }
    </style>
  </head>
  <body>
    <div class="header">
      <div class="title">تقرير توزيع الميراث الشرعي</div>
      <div class="subtitle">حسب المذهب ${madhab} – ${today}</div>
      <div class="case-number">رقم الحالة: ${caseNumber}</div>
    </div>
    <div class="section">
      <h3>ملخص التركة</h3>
      <p>صافي التركة: ${formatCurrency(result.netEstate || result.netTotal)}</p>
    </div>
    <div class="section">
      <h3>توزيع الورثة</h3>
      <table class="table">
        <thead><tr><th>الوارث</th><th>المبلغ</th><th>الكسر</th></tr></thead>
        <tbody>
          ${result.shares.map((s: any) => `
            <tr>
              <td>${s.name}</td>
              <td>${formatCurrency(s.amount)}</td>
              <td>${s.fraction.numerator}/${s.fraction.denominator}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
    <div class="signature">
      <p>تم إنشاء هذا التقرير بواسطة تطبيق ميراث</p>
      <p>لمزيد من المعلومات: support@merath.app</p>
    </div>
    <div class="disclaimer">${disclaimer}</div>
  </body>
  </html>`;

  const { uri } = await Print.printToFileAsync({ html });
  if (Platform.OS === 'android' && await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri);
  } else {
    Alert.alert('تم حفظ التقرير', `تم حفظ التقرير في: ${uri}`);
  }
}
REPORT_EOF

# ----------------------------------------------------------------------
# 3. Add educational tutorial component (first-run onboarding)
# ----------------------------------------------------------------------
echo "3. Adding educational tutorial (first-run walkthrough)..."

cat > components/EducationalTutorial.tsx << 'TUT_EOF'
import React, { useEffect, useState } from 'react';
import { View, Text, Modal, TouchableOpacity, StyleSheet, Dimensions } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useAppTheme } from '../hooks/useAppTheme';

const slides = [
  { title: 'مرحباً بك في ميراث', content: 'تطبيق متخصص لحساب المواريث الشرعية وفق المذاهب الأربعة.' },
  { title: 'الخطوة 1: أدخل التركة', content: 'أدخل إجمالي التركة، تكاليف التجهيز، الديون، والوصية (الحد الأقصى ثلث الباقي).' },
  { title: 'الخطوة 2: اختر المذهب', content: 'اختر المذهب الفقهي الذي تتبعه (حنفي، مالكي، شافعي، حنبلي).' },
  { title: 'الخطوة 3: حدد الورثة', content: 'أضف الورثة وحدد أعدادهم. سيتم تطبيق الحجب تلقائياً.' },
  { title: 'النتائج والمشاركة', content: 'اطلع على التوزيع المفصل، قارن بين المذاهب، وشارك التقرير القانوني.' },
];

const { width } = Dimensions.get('window');

export const EducationalTutorial = () => {
  const theme = useAppTheme();
  const [visible, setVisible] = useState(false);
  const [step, setStep] = useState(0);

  useEffect(() => {
    AsyncStorage.getItem('merath_tutorial_seen').then(val => {
      if (!val) setVisible(true);
    });
  }, []);

  const next = () => {
    if (step < slides.length - 1) {
      setStep(step + 1);
    } else {
      AsyncStorage.setItem('merath_tutorial_seen', 'true');
      setVisible(false);
    }
  };

  if (!visible) return null;

  return (
    <Modal transparent animationType="fade" visible={visible}>
      <View style={styles.overlay}>
        <View style={[styles.container, { backgroundColor: theme.colors.surface }]}>
          <Text style={[theme.typography.h2, { textAlign: 'center', marginBottom: 16 }]}>{slides[step].title}</Text>
          <Text style={[theme.typography.body, { textAlign: 'center', marginBottom: 24 }]}>{slides[step].content}</Text>
          <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
            <TouchableOpacity onPress={() => setVisible(false)}>
              <Text style={{ color: theme.colors.error }}>تخطي</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={next}>
              <Text style={{ color: theme.colors.primary, fontWeight: 'bold' }}>
                {step === slides.length - 1 ? 'إنهاء' : 'التالي'}
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center',
  },
  container: {
    width: width * 0.8, padding: 24, borderRadius: 16, alignItems: 'center',
  },
});
TUT_EOF

# Import and use EducationalTutorial in App.tsx (after RootNavigator)
if ! grep -q "EducationalTutorial" App.tsx; then
  sed -i '/import { ErrorBoundary }/a import { EducationalTutorial } from "./components/EducationalTutorial";' App.tsx
  sed -i '/<RootNavigator \/>/a       <EducationalTutorial />' App.tsx
fi

# ----------------------------------------------------------------------
# 4. Integrate Sentry for crash reporting (optional)
# ----------------------------------------------------------------------
echo "4. Integrating Sentry crash reporting (optional)..."

# Install Sentry packages
npm install --save expo-sentry @sentry/react-native 2>/dev/null || echo "⚠️ Could not install Sentry – skipping."

# Create sentry configuration
cat > sentry.properties << 'SENTRY_EOF'
# This file is generated – replace with your actual DSN later
SENTRY_EOF

# Add Sentry init to App.tsx
if ! grep -q "Sentry.init" App.tsx; then
  sed -i '1i import * as Sentry from "sentry-expo";' App.tsx
  sed -i '2i Sentry.init({ dsn: "YOUR_DSN_HERE", enableInExpoDevelopment: true });' App.tsx
  echo "⚠️ Remember to replace YOUR_DSN_HERE with your actual Sentry DSN (from sentry.io)."
fi

# ----------------------------------------------------------------------
# 5. Add missing test for edge cases (placeholder – requires manual writing)
# ----------------------------------------------------------------------
echo "5. Adding placeholder for missing edge-case tests..."
cat >> __tests__/edge-cases.test.ts << 'TEST_EOF'
import { describe, it, expect } from 'vitest';
// TODO: Add missing edge-case tests (e.g., Awl with many heirs, Radd with spouse, etc.)
describe('Edge Cases (to be implemented)', () => {
  it('should handle Awl with many heirs', () => {
    expect(true).toBe(true);
  });
});
TEST_EOF

# ----------------------------------------------------------------------
# Final instructions
# ----------------------------------------------------------------------
echo ""
echo "✅ Automation completed."
echo "⚠️ Manual steps still required:"
echo "   - Check lib/i18n/locales/ur.json and ms.json – if auto-translation failed, translate manually."
echo "   - Test the educational tutorial by clearing AsyncStorage or running app fresh."
echo "   - Replace 'YOUR_DSN_HERE' in App.tsx with your Sentry DSN (or remove Sentry if not needed)."
echo "   - Run 'npm test' to confirm no regressions."
echo "   - Create store assets (icons, screenshots) manually."
echo ""
echo "Run 'npx expo start --clear' to test all new features."