/**
 * Excel/CSV Export Functionality for Inheritance Calculations
* تصدير حسابات المواريث إلى Excel/CSV
 *
 * This module provides functionality to export calculation results to CSV format
 * (which can be opened in Excel, Google Sheets, and other spreadsheet applications).
 *
 * @module lib/export/ExcelExporter
 */

import type { CalculationResult, EstateInput, HeirEntry } from '../engine/types';
import { MADHAB_NAMES } from '../lib/engine/constants';

/**
 * Export format options
 */
export type ExportFormat = 'csv' | 'json' | 'txt';

/**
 * Export configuration
 */
export interface ExportConfig {
  /** Include calculation steps in export */
  includeSteps?: boolean;
  /** Include special cases analysis */
  includeSpecialCases?: boolean;
  /** Include confidence score */
  includeConfidence?: boolean;
  /** Include performance metrics */
  includePerformance?: boolean;
  /** Language for export (default: English) */
  language?: 'en' | 'ar';
  /** Currency symbol */
  currencySymbol?: string;
}

/**
 * Export data structure
 */
export interface ExportData {
  /** Export timestamp */
  timestamp: string;
  /** Estate information */
  estate: EstateInput;
  /** Heirs information */
  heirs: HeirEntry[];
  /** Calculation result */
  result: CalculationResult;
  /** Export configuration used */
  config: ExportConfig;
}

/**
 * Main exporter class
 */
export class CalculationExporter {
  /**
   * Export calculation result to CSV format
   *
   * @param data - Calculation data to export
   * @param config - Export configuration
   * @returns CSV string
   */
  public static exportToCSV(data: ExportData, config: ExportConfig = {}): string {
    const { result, estate, heirs } = data;
    const currencySymbol = config.currencySymbol || '$';

    // Build CSV content
    const csvRows: string[] = [];

    // Header section
    csvRows.push('Islamic Inheritance Calculation Export');
    csvRows.push('Exported: ' + new Date().toISOString());
    csvRows.push('');

    // Estate information
    csvRows.push('Estate Information');
    csvRows.push('Total Estate,' + currencySymbol + estate.total);
    csvRows.push('Funeral Expenses,' + currencySymbol + estate.funeral);
    csvRows.push('Debts,' + currencySymbol + estate.debts);
    csvRows.push('Will/Bequest,' + currencySymbol + estate.will);
    csvRows.push('Net Estate,' + currencySymbol + (result.netEstate || 'N/A'));
    csvRows.push('');

    // Calculation summary
    csvRows.push('Calculation Summary');
    csvRows.push('Madhab,' + MADHAB_NAMES[result.madhab]);
    csvRows.push('Success,' + (result.success ? 'Yes' : 'No'));
    csvRows.push('Confidence Score,' + (result.confidence?.toFixed(2) || 'N/A'));
    csvRows.push('Calculation Time,' + result.calculationTime + 'ms');
    csvRows.push('');

    // Heirs table
    csvRows.push('Heirs Distribution');
    csvRows.push('Heir Name,Heir Type,Count,Fraction,Percentage,Amount,Share Type');

    result.shares.forEach((share) => {
      const fraction = share.fraction
        ? share.fraction.numerator + '/' + share.fraction.denominator
        : 'N/A';
      const percentage = share.percentage ? share.percentage + '%' : 'N/A';
      const amount = share.amount ? currencySymbol + share.amount.toFixed(2) : 'N/A';

      csvRows.push(
        '"' + share.name + '","' + (share.key || 'N/A') + '",' + (share.count || 1) + ',' + fraction + ',' + percentage + ',' + amount + ',"' + (share.shareType || 'N/A') + '"'
      );
    });

    csvRows.push('');

    // Footer
    csvRows.push('');
    csvRows.push('Generated by Merath - Islamic Inheritance Calculator');
    csvRows.push('For accurate calculations, consult with Islamic scholars');

    return csvRows.join('\n');
  }

  /**
   * Export calculation result to JSON format
   *
   * @param data - Calculation data to export
   * @param config - Export configuration
   * @returns JSON string
   */
  public static exportToJSON(data: ExportData, config: ExportConfig = {}): string {
    const exportObj = {
      metadata: {
        exportedAt: new Date().toISOString(),
        appVersion: '1.0.0',
        format: 'merath-calculation-export',
      },
      estate: data.estate,
      heirs: data.heirs,
      result: {
        ...data.result,
        // Optional fields based on config
        steps: config.includeSteps ? data.result.steps : undefined,
        confidenceFactors: config.includeConfidence ? data.result.confidenceFactors : undefined,
      },
      config: config,
    };

    return JSON.stringify(exportObj, null, 2);
  }

  /**
   * Export calculation result to plain text format (SIMPLIFIED)
   *
   * @param data - Calculation data to export
   * @param config - Export configuration
   * @returns Text string
   */
  public static exportToText(data: ExportData, config: ExportConfig = {}): string {
    const { result, estate, heirs } = data;
    const currencySymbol = config.currencySymbol || '$';

    let text = 'ISLAMIC INHERITANCE CALCULATION REPORT\n';
    text += '========================================\n\n';
    text += 'Generated: ' + new Date().toISOString() + '\n';
    text += 'Madhab: ' + MADHAB_NAMES[result.madhab] + '\n';
    text += 'Total Estate: ' + currencySymbol + estate.total + '\n';
    text += 'Net Estate: ' + currencySymbol + (result.netEstate || 0) + '\n\n';
    text += 'Heirs Distribution:\n';

    result.shares.forEach((share) => {
      const amount = share.amount ? currencySymbol + share.amount.toFixed(2) : 'N/A';
      text += '- ' + share.name + ': ' + amount + '\n';
    });

    text += '\nGenerated by Merath - Islamic Inheritance Calculator';
    return text;
  }

  /**
   * Export calculation result based on format
   *
   * @param data - Calculation data to export
   * @param format - Export format
   * @param config - Export configuration
   * @returns Exported string
   */
  public static export(
    data: ExportData,
    format: ExportFormat = 'csv',
    config: ExportConfig = {}
  ): string {
    switch (format) {
      case 'csv':
        return this.exportToCSV(data, config);
      case 'json':
        return this.exportToJSON(data, config);
      case 'txt':
        return this.exportToText(data, config);
      default:
        return this.exportToCSV(data, config);
    }
  }

  /**
   * Generate filename for export
   *
   * @param format - Export format
   * @param madhab - Madhab used
   * @returns Suggested filename
   */
  public static generateFilename(
    format: ExportFormat = 'csv',
    madhab?: string
  ): string {
    const date = new Date();
    const dateStr = date.toISOString().split('T')[0];
    const madhabStr = madhab ? '_' + madhab : '';

    switch (format) {
      case 'csv':
        return 'inheritance_calculation' + madhabStr + '_' + dateStr + '.csv';
      case 'json':
        return 'inheritance_calculation' + madhabStr + '_' + dateStr + '.json';
      case 'txt':
        return 'inheritance_calculation' + madhabStr + '_' + dateStr + '.txt';
      default:
        return 'inheritance_calculation' + madhabStr + '_' + dateStr + '.csv';
    }
  }

  /**
   * Create export data structure from calculation components
   *
   * @param estate - Estate input
   * @param heirs - Heirs array
   * @param result - Calculation result
   * @returns Export data
   */
  public static createExportData(
    estate: EstateInput,
    heirs: HeirEntry[],
    result: CalculationResult
  ): ExportData {
    return {
      timestamp: new Date().toISOString(),
      estate,
      heirs,
      result,
      config: {},
    };
  }
}

/**
 * Convenience function to export calculation
 *
 * @param estate - Estate input
 * @param heirs - Heirs array
 * @param result - Calculation result
 * @param format - Export format
 * @param config - Export configuration
 * @returns Exported string and filename
 */
export function exportCalculation(
  estate: EstateInput,
  heirs: HeirEntry[],
  result: CalculationResult,
  format: ExportFormat = 'csv',
  config: ExportConfig = {}
): { content: string; filename: string } {
  const data = CalculationExporter.createExportData(estate, heirs, result);
  const content = CalculationExporter.export(data, format, config);
  const filename = CalculationExporter.generateFilename(format, result.madhab);

  return { content, filename };
}