import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform, Alert } from 'react-native';
import { formatCurrency } from '../lib/utils/currency';

export async function generateLegalReport(result: any, madhab: string) {
  const today = new Date().toLocaleDateString('ar-EG', { year: 'numeric', month: 'long', day: 'numeric' });
  const caseNumber = `MER-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
  const disclaimer = `هذا التقرير تم إنشاؤه بواسطة تطبيق "ميراث" (Merath). 
  يرجى مراجعة عالم شرعي موثوق لتأكيد صحة التوزيع. 
  This report is generated by Merath App. Please consult a qualified scholar for legal validation.`;

  const html = `
  <html>
  <head>
    <meta charset="UTF-8">
    <style>
      body { font-family: 'Arial', 'Tahoma', sans-serif; padding: 30px; direction: rtl; }
      .header { text-align: center; border-bottom: 2px solid #0D7C66; padding-bottom: 10px; margin-bottom: 20px; }
      .title { font-size: 24px; font-weight: bold; color: #0D7C66; }
      .subtitle { font-size: 14px; color: #666; }
      .case-number { font-size: 12px; color: #999; text-align: left; direction: ltr; margin-top: 5px; }
      .section { margin-bottom: 20px; }
      .table { width: 100%; border-collapse: collapse; }
      .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: right; }
      .table th { background-color: #0D7C66; color: white; }
      .signature { margin-top: 40px; border-top: 1px solid #000; padding-top: 10px; font-size: 12px; text-align: center; }
      .disclaimer { margin-top: 20px; font-size: 10px; color: #777; text-align: center; }
    </style>
  </head>
  <body>
    <div class="header">
      <div class="title">تقرير توزيع الميراث الشرعي</div>
      <div class="subtitle">حسب المذهب ${madhab} – ${today}</div>
      <div class="case-number">رقم الحالة: ${caseNumber}</div>
    </div>
    <div class="section">
      <h3>ملخص التركة</h3>
      <p>صافي التركة: ${formatCurrency(result.netEstate || result.netTotal)}</p>
    </div>
    <div class="section">
      <h3>توزيع الورثة</h3>
      <table class="table">
        <thead><tr><th>الوارث</th><th>المبلغ</th><th>الكسر</th></tr></thead>
        <tbody>
          ${result.shares.map((s: any) => `
            <tr>
              <td>${s.name}</td>
              <td>${formatCurrency(s.amount)}</td>
              <td>${s.fraction.numerator}/${s.fraction.denominator}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
    <div class="signature">
      <p>تم إنشاء هذا التقرير بواسطة تطبيق ميراث</p>
      <p>لمزيد من المعلومات: support@merath.app</p>
    </div>
    <div class="disclaimer">${disclaimer}</div>
  </body>
  </html>`;

  const { uri } = await Print.printToFileAsync({ html });
  if (Platform.OS === 'android' && await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri);
  } else {
    Alert.alert('تم حفظ التقرير', `تم حفظ التقرير في: ${uri}`);
  }
}
